ptf_admin_index:
    pattern: /
    defaults:  { _controller: PortfolioLaureBundle:Default:admin }

PortfolioLaureBundle_workexperience:
    resource: "@PortfolioLaureBundle/Resources/config/routing/workexperience.yml"
    prefix:   /workexperience

PortfolioLaureBundle_workexperienceintro:
    resource: "@PortfolioLaureBundle/Resources/config/routing/workexperienceintro.yml"
    prefix:   /workexperienceintro

PortfolioLaureBundle_workexperiencecv:
    resource: "@PortfolioLaureBundle/Resources/config/routing/workexperiencecv.yml"
    prefix:   /workexperiencecv

PortfolioLaureBundle_workexperiencenb:
    resource: "@PortfolioLaureBundle/Resources/config/routing/workexperiencenb.yml"
    prefix:   /workexperiencenb

PortfolioLaureBundle_socialnetwork:
    resource: "@PortfolioLaureBundle/Resources/config/routing/socialnetwork.yml"
    prefix:   /socialnetwork

PortfolioLaureBundle_aboutintro:
    resource: "@PortfolioLaureBundle/Resources/config/routing/aboutintro.yml"
    prefix:   /aboutintro

PortfolioLaureBundle_aboutfeeling:
    resource: "@PortfolioLaureBundle/Resources/config/routing/aboutfeeling.yml"
    prefix:   /aboutfeeling

PortfolioLaureBundle_illustration:
    resource: "@PortfolioLaureBundle/Resources/config/routing/illustration.yml"
    prefix:   /illustration

PortfolioLaureBundle_portfolio:
    resource: "@PortfolioLaureBundle/Resources/config/routing/portfolio.yml"
    prefix:   /portfolio