ptf_admin_index:
    pattern: /
    defaults:  { _controller: PortfolioLaureBundle:Default:admin }

PortfolioLaureBundle_workexperience:
    resource: "@PortfolioLaureBundle/Resources/config/routing/workexperience.yml"
    prefix:   /workexperience

PortfolioLaureBundle_workexperienceintro:
    resource: "@PortfolioLaureBundle/Resources/config/routing/workexperienceintro.yml"
    prefix:   /workexperienceintro